# Setup
url: https://iwannabethekappa.github.io/Pro-g-ramming-Challenges-v4.0
paginate: 1
baseurl: "/Pro-g-ramming-Challenges-v4.0"
permalink: pretty


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: ётка

# Custom vars
version: 3.0.0
